version: '3.7'

services:
  zawjen-postgres-db:
    image: postgres:16.2
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - zawjen-net

  kong-migrations:
    image: kong/kong-gateway:3.9.0.1
    depends_on: 
      - zawjen-postgres-db
    environment:
      KONG_DATABASE: ${KONG_DATABASE}
      KONG_PG_HOST: ${KONG_PG_HOST}
      KONG_PG_USER: ${KONG_PG_USER}
      KONG_PG_PASSWORD: ${KONG_PG_PASSWORD}
      KONG_PASSWORD: ${KONG_PASSWORD}
    networks:
      - zawjen-net
    command: kong migrations bootstrap

  kong-gateway:
    image: kong/kong-gateway:3.9.0.1
    container_name: kong-gateway
    depends_on: 
      - kong-migrations
      - zawjen-postgres-db
    restart: always
    networks:
      - zawjen-net
    environment:
      KONG_DATABASE: ${KONG_DATABASE}
      KONG_PG_DATABASE: ${KONG_PG_DATABASE}
      KONG_PG_HOST: ${KONG_PG_HOST}
      KONG_PG_USER: ${KONG_PG_USER}
      KONG_PG_PASSWORD: ${KONG_PG_PASSWORD}
      KONG_PROXY_ACCESS_LOG: "/dev/stdout"
      KONG_ADMIN_ACCESS_LOG: "/dev/stdout"
      KONG_PROXY_ERROR_LOG: "/dev/stderr"
      KONG_ADMIN_ERROR_LOG: "/dev/stderr"
      KONG_ADMIN_LISTEN: "0.0.0.0:8001"
      KONG_ADMIN_GUI_URL: "http://localhost:8002"
      KONG_LICENSE_DATA: 
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8444:8444"
      - "8002:8002"
      - "8445:8445"
      - "8003:8003"
      - "8004:8004"

  keycloak:
    image: quay.io/keycloak/keycloak:23.0.6
    depends_on: 
      - zawjen-postgres-db
    environment:
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8080
      KC_HOSTNAME_STRICT_BACKCHANNEL: false
      KC_HTTP_ENABLED: true
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HEALTH_ENABLED: true
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://${KEYCLOAK_PG_HOST}/${KEYCLOAK_PG_DATABASE}
      KC_DB_USERNAME: ${KEYCLOAK_PG_USER}
      KC_DB_PASSWORD: ${KEYCLOAK_PG_PASSWORD}
    ports:
      - 8080:8080
    restart: always
    networks:
      - zawjen-net
    command: start

volumes:
  postgres_data:
    driver: local

networks:
  zawjen-net:
    driver: bridge